%YAML:1.0
chisquare_file: /opt/tros/lib/hobot_vio/config/chisquare_check.txt
downsample: 1
num_pts: 250
gravity: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.0, 0.0, 9.80665]
gyroscope_noise_density: 0.00182936867769
gyroscope_random_walk: 2.84378581073e-05
accelerometer_noise_density: 0.011496108364
accelerometer_random_walk: 0.00027
init_imu_thresh: 0.4
fast_threshold: 15
# camera intrinsics
cam_width: 640
cam_height: 480
cam_k: !!opencv-matrix
  rows: 4
  cols: 1
  dt: d
  data: [585.75, 586.55, 317.03, 232.14]
cam_d: !!opencv-matrix
  rows: 4
  cols: 1
  dt: d
  data: [0.11333168474163988, -0.2257716479153822, -0.0050474045563873, -0.0049706898895231135]

# camera-imu extrinsics
T_CtoI: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [
    0.99993386, -0.01040667, -0.00489613, -0.02735635,
    0.01035866, 0.999899, -0.00973073, 0.00194134,
    0.0049969, 0.00967937, 0.99994067, 0.05170289,
    0.0, 0.0, 0.0, 1.0]

